"""
Django settings for reserish project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS","nkc.buzz 127.0.0.1 localhost 13.234.19.252 13.232.122.71 66.179.211.82  reserishmain.nkc.buzz  reserishmain.nkcs.site").split()

# Frontend URL for referral links
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")
# ALLOWED_HOSTS = [
#     'localhost',
#     'nkc.buzz',
#     '127.0.0.1',
#     'localhost',
#     'hiresmarts.in',
#     'reserishmain.nkc.buzz']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'backend',
    'django_celery_results',
    'django_celery_beat',
    'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'backend.middleware.restrict_admin.RestrictAdminMiddleware',
]

ROOT_URLCONF = 'reserish.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join(BASE_DIR, 'backend/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'backend/static'),
]

WSGI_APPLICATION = 'reserish.wsgi.application'

CRON_CLASSES = [
    "backend.tasks.CheckPlanExpiries",
]

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("POSTGRES_DB"),
        'USER': os.getenv("POSTGRES_USER"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
        'HOST': os.getenv("POSTGRES_HOST"),  # Set to the address of your PostgreSQL server
        'PORT': os.getenv("POSTGRES_PORT"),       # Set to the port your PostgreSQL server is running on
        'OPTIONS': {
            # Disable unix socket completely
            'connect_timeout': 3,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True # Or specify allowed origins
# CORS_ALLOW_METHODS = [
#     "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# ]

# CORS_ALLOWED_ORIGINS = [
#     # Add the domains from which your frontend will make requests
#     "http://localhost:3001",
#     "http://localhost:5173",
#     'http://13.234.19.252:8000',
#     'http://13.232.122.71:8000',
#     'http://66.179.211.82:8000',
#     'https://reserishmain.nkc.buzz',
#     'http://reserishmain.nkc.buzz',
#     # Add more origins as needed
# ]


# Allow credentials (cookies, authentication headers, etc.)
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = True


MEDIA_ROOT = BASE_DIR / "media"  # adjust the path as needed
MEDIA_PUBLIC= BASE_DIR / "media/latex_templates"
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'backend.CustomUser'

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = True
SESSION_COOKIE_AGE = 1209600 
# X_FRAME_OPTIONS = 'DENY'
X_FRAME_OPTIONS = 'ALLOWALL'


# SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# SESSION_ENGINE ="backend.fallback_sessions"
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
if os.getenv("REDIS_CLUSTER","True").lower()=="false":
    CACHES = {
        "default": {
            # "BACKEND": "django_redis.cache.RedisCache",
            # "LOCATION": os.getenv("REDIS_SESSION_URL","redis://redis:6379/1"),
            # "OPTIONS": {
            #     "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # }
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv("REDIS_SESSION_URL","redis://redis:6379/1"),
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": [
                f"redis://{os.getenv('REDIS_SERVICE','session-redis')}-0.{os.getenv('REDIS_SERVICE','session-redis')}:6379/0",
                f"redis://{os.getenv('REDIS_SERVICE','session-redis')}-1.{os.getenv('REDIS_SERVICE','session-redis')}:6379/0",
                f"redis://{os.getenv('REDIS_SERVICE','session-redis')}-2.{os.getenv('REDIS_SERVICE','session-redis')}:6379/0"
            ],
            'OPTIONS': {
                'REDIS_CLIENT_CLASS': 'django_cluster_redis.cache.ClusterRedis',
            },
        }
    }


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    #  'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # )
}
SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
}
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Keep this for admin
]

ALLOWED_ADMIN_DOMAINS = ["localhost","127.0.0.1",'local.nkcs.site'] 

# Allow Django to share cookies across HTTPS sites
CSRF_COOKIE_SAMESITE = "Lax"   # Or 'None' if cross-origin
SESSION_COOKIE_SAMESITE = "Lax"

# Required for cross-site trust (only if accessing admin via a different domain)
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS","https://nkc.buzz/  https://reserishmain.nkc.buzz/ https://kreserishmain.nkc.buzz").split()

# Celery Configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL",'redis://localhost:6379')
CELERY_RESULT_BACKEND = os.getenv("CELERY_BROKER_URL",'redis://localhost:6379')

accept_content = ['application/json']
task_serializer = 'json'
result_serializer = 'json'
timezone = 'Asia/Kolkata'
result_backend='django-db'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

FRONTEND_URL=os.getenv('FRONTEND_URL')
EFRONTEND_URL=os.getenv('EFRONTEND_URL')


# Email Configuration 
DEFAULT_FROM_EMAIL = ''
DEFAULT_SUPPORT_EMAIL = ''
DEFAULT_DOMAIN = FRONTEND_URL  # Your production domain
SITE_NAME = 'Reserish'

EMAIL_BACKEND = ['django.core.mail.backends.console.EmailBackend', 
                 'django.core.mail.backends.smtp.EmailBackend'][int(os.getenv("ENABLE_MAIL", "1"))]

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_PORT = 587
E_EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER",)
E_EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")



#dw5?dUn8KUF6z^*
RAZORPAY_API_KEY=os.getenv("RAZORPAY_API_KEY_TEST")
RAZORPAY_API_SECRET=os.getenv("RAZORPAY_API_SECRET_TEST")

CASHFREE_MODE=os.getenv("CASHFREE_MODE",'TEST')
RAZORPAY_MODE=os.getenv("RAZORPAY_MODE",'TEST')

CASHFREE_APP_ID = os.getenv("CASHFREE_APP_ID_TEST")
CASHFREE_SECRET_KEY = os.getenv("CASHFREE_SECRET_KEY_TEST")
CASHFREE_BASE_URL = os.getenv("CASHFREE_BASE_URL_TEST",'https://sandbox.cashfree.com/pg')

if CASHFREE_MODE=="PROD":
    CASHFREE_APP_ID = os.getenv("CASHFREE_APP_ID")
    CASHFREE_SECRET_KEY = os.getenv("CASHFREE_SECRET_KEY")
    CASHFREE_BASE_URL = os.getenv("CASHFREE_BASE_URL",'https://api.cashfree.com/pg')

if RAZORPAY_MODE=="PROD":
    RAZORPAY_API_KEY=os.getenv("RAZORPAY_API_KEY")
    RAZORPAY_API_SECRET=os.getenv("RAZORPAY_API_SECRET")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

USE_MONGO=os.getenv("USE_MONGO","True").lower()=="true"
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/")
MONGO_DB  = os.getenv("MONGO_DB", "reserish_log")

# LOGGING = {
#     'version': 1,
#     'handlers': {
#         'console': {'class': 'logging.StreamHandler'},
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'DEBUG',
#     },
# }
