#!/usr/bin/env python3
"""
Setup script for configuring Groq API keys.
This script helps users set up multiple API keys for automatic rotation.
"""

import os
import sys
from pathlib import Path

def create_env_file():
    """Create a .env file with API key configuration"""
    env_path = Path(__file__).parent / ".env"
    
    if env_path.exists():
        print(f"⚠️  .env file already exists at {env_path}")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    print("🔑 Groq API Key Setup")
    print("=" * 50)
    print("This script will help you configure multiple Groq API keys for automatic rotation.")
    print("Each key will be used for up to 1000 calls before automatically switching to the next.")
    print()
    
    # Get API keys from user
    api_keys = []
    
    # Primary key (required)
    while True:
        primary_key = input("Enter your primary Groq API key (starts with 'gsk_'): ").strip()
        if primary_key.startswith('gsk_'):
            api_keys.append(primary_key)
            break
        else:
            print("❌ Invalid API key format. Groq API keys should start with 'gsk_'")
    
    # Additional keys (optional)
    print("\n💡 You can add additional API keys for automatic rotation.")
    print("   Press Enter without typing anything to skip additional keys.")
    
    key_num = 1
    while True:
        additional_key = input(f"Enter additional API key {key_num} (or press Enter to finish): ").strip()
        if not additional_key:
            break
        
        if additional_key.startswith('gsk_'):
            api_keys.append(additional_key)
            key_num += 1
            if key_num > 10:
                print("✅ Maximum of 10 API keys reached.")
                break
        else:
            print("❌ Invalid API key format. Groq API keys should start with 'gsk_'")
    
    # Get custom call limit
    print("\n⚙️  Call limit configuration:")
    print("   Each API key will be used for a maximum number of calls before rotation.")
    try:
        custom_limit = input("Enter custom call limit per key (default: 1000): ").strip()
        if custom_limit:
            call_limit = int(custom_limit)
        else:
            call_limit = 1000
    except ValueError:
        print("⚠️  Invalid number, using default limit of 1000")
        call_limit = 1000
    
    # Create .env file content
    env_content = f"""# Groq API Keys Configuration
# Generated by setup_api_keys.py

# Primary API key
GROQ_API_KEY={api_keys[0]}

# Additional API keys for automatic rotation
"""
    
    for i, key in enumerate(api_keys[1:], 1):
        env_content += f"GROQ_API_KEY_{i}={key}\n"
    
    env_content += f"""
# Custom call limit per key
GROQ_MAX_CALLS_PER_KEY={call_limit}

# Note: Keep this file secure and never commit it to version control
"""
    
    # Write .env file
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        print(f"\n✅ .env file created successfully at {env_path}")
        print(f"📊 Configuration:")
        print(f"   Total API keys: {len(api_keys)}")
        print(f"   Call limit per key: {call_limit}")
        print(f"   Total capacity: {len(api_keys) * call_limit:,} calls")
        
        if len(api_keys) > 1:
            print(f"\n🔄 Automatic rotation will occur every {call_limit} calls")
            print(f"   Keys will rotate in this order: 1 → 2 → 3... → {len(api_keys)} → 1")
        
        print(f"\n🚀 You're all set! The system will automatically use these API keys.")
        print(f"   To test the setup, run: python test_api_manager.py")
        print(f"   To manage keys via Django: python manage.py manage_groq_keys status")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return

def validate_env_file():
    """Validate existing .env file"""
    env_path = Path(__file__).parent / ".env"
    
    if not env_path.exists():
        print("❌ No .env file found.")
        return False
    
    print("🔍 Validating .env file...")
    
    # Load environment variables
    load_dotenv(env_path)
    
    # Check for API keys
    api_keys = []
    base_key = os.getenv("GROQ_API_KEY")
    if base_key:
        api_keys.append(base_key)
    
    for i in range(1, 11):
        additional_key = os.getenv(f"GROQ_API_KEY_{i}")
        if additional_key:
            api_keys.append(additional_key)
    
    if not api_keys:
        print("❌ No API keys found in .env file")
        return False
    
    print(f"✅ Found {len(api_keys)} API key(s)")
    
    # Validate key format
    invalid_keys = [key for key in api_keys if not key.startswith('gsk_')]
    if invalid_keys:
        print(f"⚠️  {len(invalid_keys)} invalid API key(s) found (should start with 'gsk_')")
        return False
    
    print("✅ All API keys have valid format")
    
    # Check call limit
    call_limit = os.getenv("GROQ_MAX_CALLS_PER_KEY", "1000")
    try:
        limit = int(call_limit)
        print(f"✅ Call limit per key: {limit:,}")
        print(f"📊 Total capacity: {len(api_keys) * limit:,} calls")
    except ValueError:
        print("⚠️  Invalid call limit format")
        return False
    
    return True

def main():
    """Main function"""
    print("🚀 Groq API Key Setup Utility")
    print("=" * 50)
    
    if len(sys.argv) > 1 and sys.argv[1] == "validate":
        # Import dotenv for validation
        try:
            from dotenv import load_dotenv
            validate_env_file()
        except ImportError:
            print("❌ python-dotenv not installed. Install with: pip install python-dotenv")
        return
    
    # Check if .env already exists
    env_path = Path(__file__).parent / ".env"
    if env_path.exists():
        print(f"📁 .env file found at {env_path}")
        response = input("Do you want to create a new one? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    create_env_file()

if __name__ == "__main__":
    main()

